- platform: history_stats
  entity_id: climate.upstairs_hall_cooling_1
  name: Cooling On
  state: 'cool'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24

- platform: history_stats
  entity_id: climate.family_room_heating_1
  name: Heating On
  state: 'heat'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24
