- platform: template
  sensors:
#
# Smoke Alarms
#
##    {% for state in expand('group.smoke_detectors') %}
##    {%- set name = state.entity_id.split('.')[1] %}
##    {%- set friendly_name = name.replace("_", " ").title() %}
##    {%- set state_name = 'sensor.' + name +'_alarm_type' %}
##    {{ name + ':' }}
##      friendly_name: {{ friendly_name }}
##      value_template: >-
##        {{ "{%" }} set alarm_type = states('{{ state_name }}')|int('unknown') %}
##        {{ "{%" }} if alarm_type == 13 %}
##          Idle
##        {{ "{%" }} elif alarm_type == 12 %}
##          Testing
##        {{ "{%" }} elif alarm_type == 1 %}
##          Fire
##        {{ "{%" }} elif alarm_type == 0 %}
##          CO
##        {{ "{%" }} else %}
##          Unknown
##        {{ "{%" }} endif %}
##    {% endfor %}
    smoke_detector_basement:
      friendly_name: Smoke Detector Basement
      value_template: >-
        {% set alarm_type = states('sensor.smoke_detector_basement_alarm_type')|int('unknown') %}
        {% if alarm_type == 13 %}
          Idle
        {% elif alarm_type == 12 %}
          Testing
        {% elif alarm_type == 1 %}
          Fire
        {% elif alarm_type == 0 %}
          CO
        {% else %}
          Unknown
        {% endif %}
    
    smoke_detector_dining_room:
      friendly_name: Smoke Detector Dining Room
      value_template: >-
        {% set alarm_type = states('sensor.smoke_detector_dining_room_alarm_type')|int('unknown') %}
        {% if alarm_type == 13 %}
          Idle
        {% elif alarm_type == 12 %}
          Testing
        {% elif alarm_type == 1 %}
          Fire
        {% elif alarm_type == 0 %}
          CO
        {% else %}
          Unknown
        {% endif %}
    
    smoke_detector_upstairs_hall:
      friendly_name: Smoke Detector Upstairs Hall
      value_template: >-
        {% set alarm_type = states('sensor.smoke_detector_upstairs_hall_alarm_type')|int('unknown') %}
        {% if alarm_type == 13 %}
          Idle
        {% elif alarm_type == 12 %}
          Testing
        {% elif alarm_type == 1 %}
          Fire
        {% elif alarm_type == 0 %}
          CO
        {% else %}
          Unknown
        {% endif %}
#
# Average Temperature Calculations
#
    basement_temp:
      friendly_name: Basement Avg. Temperature
      unit_of_measurement: "°F"
      value_template: >-
        {{ ((float(states.sensor.multisensor_basement_temperature.state)) / 1) | round(2) }}

    downstairs_temp:
      friendly_name: Downstairs Avg. Temperature
      unit_of_measurement: "°F"
      value_template: >-
        {{ ((float(states.sensor.multisensor_kitchen_temperature.state) + float(states.sensor.multisensor_family_room_temperature.state) + float(states.sensor.thermostat_family_room_temperature.state) + float(states.sensor.multisensor_living_room_temperature.state) + float(states.sensor.thermostat_living_room_temperature.state)) / 5) | round(2) }}

    upstairs_temp:
      friendly_name: Upstairs Avg. Temperature
      unit_of_measurement: "°F"
      value_template: >-
        {{ ((float(states.sensor.thermostat_master_bedroom_temperature.state) + float(states.sensor.thermostat_jake_bedroom_temperature.state) + float(states.sensor.thermostat_upstairs_hall_temperature.state)) / 3) | round(2) }}
#
# Thermostat States
#
##    {% for state in expand('group.thermostats') %}
##    {%- set name = state.entity_id.split('.')[1] %}
##    {%- set friendly_name = name.replace("_", " ").title() %}
##    {{ name }}_state:
##      friendly_name: {{ friendly_name }}
##      entity_id: climate.{{ name }}
##      value_template: >-
##        {{ "{{" }} state_attr('climate.{{ name }}', 'hvac_action') }}
##    {% endfor %}
    thermostat_family_room_state:
      friendly_name: Thermostat Family Room
      entity_id: climate.thermostat_family_room
      value_template: >-
        {{ state_attr('climate.thermostat_family_room', 'hvac_action') }}
    
    thermostat_jake_bedroom_state:
      friendly_name: Thermostat Jake Bedroom
      entity_id: climate.thermostat_jake_bedroom
      value_template: >-
        {{ state_attr('climate.thermostat_jake_bedroom', 'hvac_action') }}
    
    thermostat_living_room_state:
      friendly_name: Thermostat Living Room
      entity_id: climate.thermostat_living_room
      value_template: >-
        {{ state_attr('climate.thermostat_living_room', 'hvac_action') }}
    
    thermostat_master_bedroom_state:
      friendly_name: Thermostat Master Bedroom
      entity_id: climate.thermostat_master_bedroom
      value_template: >-
        {{ state_attr('climate.thermostat_master_bedroom', 'hvac_action') }}
    
    thermostat_upstairs_hall_state:
      friendly_name: Thermostat Upstairs Hall
      entity_id: climate.thermostat_upstairs_hall
      value_template: >-
        {{ state_attr('climate.thermostat_upstairs_hall', 'hvac_action') }}
#
# Motion Sensors
#
##    {% for state in expand('group.multisensors') %}
##    {%- set name = state.entity_id.split('.')[1] %}
##    {%- set friendly_name = name.replace("_", " ").title() %}
##    {%- set state_name = 'sensor.' + name +'_burglar' %}
##    {{ name }}_motion:
##      friendly_name: {{ friendly_name }} Motion
##      value_template: >-
##        {{ "{%" }} set burglar_type = states('{{ state_name }}')|int('unknown') %}
##        {{ "{%" }} if burglar_type == 8 %}
##          Motion
##        {{ "{%" }} elif burglar_type == 3 %}
##          Tamper
##        {{ "{%" }} else %}
##          Still
##        {{ "{%" }} endif %}
##    {% endfor %}
    multisensor_basement_motion:
      friendly_name: Multisensor Basement Motion
      value_template: >-
        {% set burglar_type = states('sensor.multisensor_basement_burglar')|int('unknown') %}
        {% if burglar_type == 8 %}
          Motion
        {% elif burglar_type == 3 %}
          Tamper
        {% else %}
          Still
        {% endif %}
    
    multisensor_family_room_motion:
      friendly_name: Multisensor Family Room Motion
      value_template: >-
        {% set burglar_type = states('sensor.multisensor_family_room_burglar')|int('unknown') %}
        {% if burglar_type == 8 %}
          Motion
        {% elif burglar_type == 3 %}
          Tamper
        {% else %}
          Still
        {% endif %}
    
    multisensor_kitchen_motion:
      friendly_name: Multisensor Kitchen Motion
      value_template: >-
        {% set burglar_type = states('sensor.multisensor_kitchen_burglar')|int('unknown') %}
        {% if burglar_type == 8 %}
          Motion
        {% elif burglar_type == 3 %}
          Tamper
        {% else %}
          Still
        {% endif %}
    
    multisensor_living_room_motion:
      friendly_name: Multisensor Living Room Motion
      value_template: >-
        {% set burglar_type = states('sensor.multisensor_living_room_burglar')|int('unknown') %}
        {% if burglar_type == 8 %}
          Motion
        {% elif burglar_type == 3 %}
          Tamper
        {% else %}
          Still
        {% endif %}
#
# ZWave Batteries - Dynamic icons seems to be supported now?
#
##    {% for state in expand('group.zwave_batteries') %}
##    {%- set name = state.entity_id.split('.')[1] %}
##    {%- set friendly_name = name.replace("_", " ").title() %}
##    {{ name }}_battery:
##      friendly_name: {{ friendly_name }} Battery
##      value_template: >-
##        {{ "{{" }}  state_attr('zwave.{{ name }}', 'battery_level')|int }}
##      unit_of_measurement: '%'
##      icon_template: >-
##        {{ "{%" }} set battery_level = states('sensor.{{ name }}_battery')|int('unknown') %}
##        {{ "{%" }} set battery_round = (battery_level|int / 10)|int * 10 %}
##        {{ "{%" }} if battery_level == 'unknown' %}
##          mdi:battery-unknown
##        {{ "{%" }} else %}
##          {{ "{%" }} if battery_round >= 100 %}
##            mdi:battery
##          {{ "{%" }} elif battery_round > 0 %}
##            mdi:battery-{{ "{{" }} battery_round }}
##          {{ "{%" }} else %}
##            mdi:battery-alert
##          {{ "{%" }} endif %}
##        {{ "{%" }} endif %}
##    {% endfor %}
#    multisensor_basement_battery:
#      friendly_name: Multisensor Basement Battery
#      value_template: >-
#        {{  state_attr('zwave.multisensor_basement', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.multisensor_basement_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    multisensor_family_room_battery:
#      friendly_name: Multisensor Family Room Battery
#      value_template: >-
#        {{  state_attr('zwave.multisensor_family_room', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.multisensor_family_room_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    multisensor_kitchen_battery:
#      friendly_name: Multisensor Kitchen Battery
#      value_template: >-
#        {{  state_attr('zwave.multisensor_kitchen', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.multisensor_kitchen_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    multisensor_living_room_battery:
#      friendly_name: Multisensor Living Room Battery
#      value_template: >-
#        {{  state_attr('zwave.multisensor_living_room', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.multisensor_living_room_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    smoke_detector_basement_battery:
#      friendly_name: Smoke Detector Basement Battery
#      value_template: >-
#        {{  state_attr('zwave.smoke_detector_basement', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.smoke_detector_basement_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    smoke_detector_dining_room_battery:
#      friendly_name: Smoke Detector Dining Room Battery
#      value_template: >-
#        {{  state_attr('zwave.smoke_detector_dining_room', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.smoke_detector_dining_room_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    smoke_detector_upstairs_hall_battery:
#      friendly_name: Smoke Detector Upstairs Hall Battery
#      value_template: >-
#        {{  state_attr('zwave.smoke_detector_upstairs_hall', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.smoke_detector_upstairs_hall_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    thermostat_family_room_battery:
#      friendly_name: Thermostat Family Room Battery
#      value_template: >-
#        {{  state_attr('zwave.thermostat_family_room', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.thermostat_family_room_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    thermostat_jake_bedroom_battery:
#      friendly_name: Thermostat Jake Bedroom Battery
#      value_template: >-
#        {{  state_attr('zwave.thermostat_jake_bedroom', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.thermostat_jake_bedroom_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    thermostat_living_room_battery:
#      friendly_name: Thermostat Living Room Battery
#      value_template: >-
#        {{  state_attr('zwave.thermostat_living_room', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.thermostat_living_room_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    thermostat_master_bedroom_battery:
#      friendly_name: Thermostat Master Bedroom Battery
#      value_template: >-
#        {{  state_attr('zwave.thermostat_master_bedroom', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.thermostat_master_bedroom_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    thermostat_upstairs_hall_battery:
#      friendly_name: Thermostat Upstairs Hall Battery
#      value_template: >-
#        {{  state_attr('zwave.thermostat_upstairs_hall', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.thermostat_upstairs_hall_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    watersensor_hot_water_battery:
#      friendly_name: Watersensor Hot Water Battery
#      value_template: >-
#        {{  state_attr('zwave.watersensor_hot_water', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.watersensor_hot_water_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    watersensor_sump_pump_battery:
#      friendly_name: Watersensor Sump Pump Battery
#      value_template: >-
#        {{  state_attr('zwave.watersensor_sump_pump', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.watersensor_sump_pump_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
#    
#    watersensor_water_tank_battery:
#      friendly_name: Watersensor Water Tank Battery
#      value_template: >-
#        {{  state_attr('zwave.watersensor_water_tank', 'battery_level')|int }}
#      unit_of_measurement: '%'
#      icon_template: >-
#        {% set battery_level = states('sensor.watersensor_water_tank_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#            mdi:battery
#          {% elif battery_round > 0 %}
#            mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}