- platform: template
  sensors:
#
# Smoke Alarms
#
    smoke_detector_basement:
      friendly_name: Smoke Detector Basement
      value_template: >-
        {% if is_state("sensor.smoke_detector_basement_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_basement_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_basement_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_basement_alarm_type", "0") %}
          CO
        {% else %}
          Unknown
        {% endif %}
    smoke_detector_foyer:
      friendly_name: Smoke Detector Foyer
      value_template: >-
        {% if is_state("sensor.smoke_detector_foyer_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_foyer_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_foyer_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_foyer_alarm_type", "0") %}
          CO
        {% else %}
          Unknown
        {% endif %}
    smoke_detector_upstairs_hall:
      friendly_name: Smoke Detector Upstairs Hall
      value_template: >-
        {% if is_state("sensor.smoke_detector_upstairs_hall_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_upstairs_hall_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_upstairs_hall_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_upstairs_hall_alarm_type", "0") %}
          CO
        {% else %}
          Unknown
        {% endif %}
#
# Average Temperature Calculations
#
    basement_temp:
      friendly_name: Basement Avg. Temperature
      unit_of_measurement: "°F"
      value_template: >-
        {{ (float(states.sensor.ms_basement_temperature.state)) / 1 | round(2) }}

    downstairs_temp:
      friendly_name: Downstairs Avg. Temperature
      unit_of_measurement: "°F"
      value_template: >-
        {{ (float(states.sensor.ms_kitchen_temperature.state) + float(states.sensor.ms_family_room_temperature.state) + float(states.sensor.climate_family_room_temperature.state) + float(states.sensor.ms_living_room_temperature.state) + float(states.sensor.climate_living_room_temperature.state)) / 5 | round(2) }}

    upstairs_temp:
      friendly_name: Upstairs Avg. Temperature
      unit_of_measurement: "°F"
      value_template: >-
        {{ (float(states.sensor.climate_master_bedroom_temperature.state) + float(states.sensor.climate_jake_bedroom_temperature.state) + float(states.sensor.climate_upstairs_hall_temperature.state)) / 3 | round(2) }}
#
# Thermostat States
#
    living_room_tstat_state:
      friendly_name: Living Room State
      entity_id: climate.living_room_heating
      value_template: >-
        {% if states.climate.living_room_heating %}
          {{ states.climate.living_room_heating.attributes.hvac_action}}
        {% else %}
          N/A
        {% endif %}

    family_room_tstat_state:
      friendly_name: Family Room State
      entity_id: climate.family_room_heating
      value_template: >-
        {% if states.climate.family_room_heating %}
          {{ states.climate.family_room_heating.attributes.hvac_action}}
        {% else %}
          N/A
        {% endif %}

    master_bedroom_tstat_state:
      friendly_name: Master Bedroom State
      entity_id: climate.master_bedroom_heating
      value_template: >-
        {% if states.climate.master_bedroom_heating %}
          {{ states.climate.master_bedroom_heating.attributes.hvac_action}}
        {% else %}
          N/A
        {% endif %}

    jake_bedroom_tstat_state:
      friendly_name: Jake Bedroom State
      entity_id: climate.jake_bedroom_heating
      value_template: >-
        {% if states.climate.jake_bedroom_heating %}
          {{ states.climate.jake_bedroom_heating.attributes.hvac_action}}
        {% else %}
          N/A
        {% endif %}

    upstairs_hall_tstat_state:
      friendly_name: Upstairs Hall State
      entity_id: climate.upstairs_hall_cooling
      value_template: >-
        {% if states.climate.upstairs_hall_cooling %}
          {{ states.climate.upstairs_hall_cooling.attributes.hvac_action}}
        {% else %}
          N/A
        {% endif %}
#
# Motion Sensors
#
    living_room_motion:
      friendly_name: Living Room Motion
      value_template: >-
        {% if is_state("sensor.ms_living_room_burglar", "8") %}
          Motion
        {% elif is_state("sensor.ms_living_room_burglar", "3") %}
          Tamper
        {% else %}
          Still
        {% endif %}
    family_room_motion:
      friendly_name: Family Room Motion
      value_template: >-
        {% if is_state("sensor.ms_family_room_burglar", "8") %}
          Motion
        {% elif is_state("sensor.ms_family_room_burglar", "3") %}
          Tamper
        {% else %}
          Still
        {% endif %}
    kitchen_motion:
      friendly_name: Kitchen Motion
      value_template: >-
        {% if is_state("sensor.ms_kitchen_burglar", "8") %}
          Motion
        {% elif is_state("sensor.ms_kitchen_burglar", "3") %}
          Tamper
        {% else %}
          Still
        {% endif %}
    basement_motion:
      friendly_name: Basement Motion
      value_template: >-
        {% if is_state("sensor.ms_basement_burglar", "8") %}
          Motion
        {% elif is_state("sensor.ms_basement_burglar", "3") %}
          Tamper
        {% else %}
          Still
        {% endif %}
