language: python
python:
    - "3.6"

before_install:
    - mv travis_secrets.yaml secrets.yaml
    - touch /tmp/test.txt
    - sed -i -e 's/device_tracker\:\s\!include\sinclude\/device_tracker.yaml'
    - sudo apt-get update && sudo apt-get install -y libudev-dev

install:
    - pip3 install homeassistant && pip3 install colorama && pip3 install colorlog

script:
    - hass -c . --script check_config
