language: python
python:
    - "3.6"

env:
  - HASS='homeassistant'
  - HASS='--pre homeassistant'

before_install:
    - mv travis_secrets.yaml secrets.yaml
    - touch /tmp/test.txt
    - sudo apt-get update && sudo apt-get install -y libudev-dev

install:
    - pip3 install $HASS && pip3 install colorama colorlog getmac==0.8.1

script:
    - hass -c . --script check_config
