- platform: generic
  still_image_url: !secret radar_url
  name: Rochester Radar

- platform: arlo

- platform: local_file
  file_path: /config/arlo-lapse/Garage.gif
  name: Garage Lapse

- platform: local_file
  file_path: /config/arlo-lapse/Front_Door.gif
  name: Front Door Lapse

- platform: local_file
  file_path: /config/arlo-lapse/Back_Door.gif
  name: Back Door Lapse

- platform: local_file
  file_path: /config/arlo-lapse/Misc.gif
  name: Misc Lapse
