#- platform: arlo
#  monitored_conditions:
#    - captured_today
#    - last_capture
#    - total_cameras
#    - battery_level

- platform: fail2ban
  jails:
    - nginx-http-auth
    - nginx-badbots
    - nginx-botsearch
    - organizr-auth
    - hass-iptables
  file_path: /fail2ban/fail2ban.log
  scan_interval: 120

- platform: google_wifi

- platform: pi_hole
  host: 192.168.86.31

- platform: history_stats
  entity_id: climate.upstairs_hall_cooling_1
  name: Cooling On
  state: 'Cool'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24

- platform: history_stats
  entity_id: climate.family_room_heating_1
  name: Heating On
  state: 'Heat'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: wunderground
  api_key: f46fc3e0accf13de
  pws_id: knyhoneo5
  monitored_conditions:
    - alerts
    - weather
    - weather_1d
    - station_id
    - temp_f
    - dewpoint_f
    - relative_humidity
    - feelslike_f
    - UV
    - wind_mph
    - wind_dir
    - precip_today_in
    - pressure_in

- platform: template
  sensors:
    basement_temp:
      friendly_name: Basement Avg. Temperature
      unit_of_measurement: "°F"
      value_template: >-
        {{ (float(states.sensor.ms_basement_temperature.state)) / 1 | round(2) }}

    downstairs_temp:
      friendly_name: Downstairs Avg. Temperature
      unit_of_measurement: "°F"
      value_template: >-
        {{ (float(states.sensor.ms_kitchen_temperature.state) + float(states.sensor.ms_family_room_temperature.state) + float(states.sensor.family_room_temperature.state) + float(states.sensor.ms_living_room_temperature.state) + float(states.sensor.living_room_temperature.state)) / 5 | round(2) }}

    upstairs_temp:
      friendly_name: Upstairs Avg. Temperature
      unit_of_measurement: "°F"
      value_template: >-
        {{ (float(states.sensor.master_bedroom_temperature.state) + float(states.sensor.jake_bedroom_temperature.state) + float(states.sensor.upstairs_hall_temperature.state)) / 3 | round(2) }}

    living_room_tstat_state:
      friendly_name: Living Room State
      entity_id: climate.living_room_heating_1
      value_template: >-
        {% if states.climate.living_room_heating_1 %}
          {{ states.climate.living_room_heating_1.attributes.operation_mode}}
        {% else %}
          N/A
        {% endif %}

    family_room_tstat_state:
      friendly_name: Family Room State
      entity_id: climate.family_room_heating_1
      value_template: >-
        {% if states.climate.family_room_heating_1 %}
          {{ states.climate.family_room_heating_1.attributes.operation_mode }}
        {% else %}
          N/A
        {% endif %}

    master_bedroom_tstat_state:
      friendly_name: Master Bedroom State
      entity_id: climate.master_bedroom_heating_1
      value_template: >-
        {% if states.climate.master_bedroom_heating_1 %}
          {{ states.climate.master_bedroom_heating_1.attributes.operation_mode }}
        {% else %}
          N/A
        {% endif %}

    jake_bedroom_tstat_state:
      friendly_name: Jake Bedroom State
      entity_id: climate.jake_bedroom_heating_1
      value_template: >-
        {% if states.climate.jake_bedroom_heating_1 %}
          {{ states.climate.jake_bedroom_heating_1.attributes.operation_mode }}
        {% else %}
          N/A
        {% endif %}

    upstairs_hall_tstat_state:
      friendly_name: Upstairs Hall State
      entity_id: climate.upstairs_hall_cooling_1
      value_template: >-
        {% if states.climate.upstairs_hall_cooling_1 %}
          {{ states.climate.upstairs_hall_cooling_1.attributes.operation_mode }}
        {% else %}
          N/A
        {% endif %}
#
# Motion Sensors
#
    living_room_motion:
      friendly_name: Living Room Motion
      value_template: >-
        {% if is_state("sensor.ms_living_room_burglar", "8") %}
          Motion
        {% elif is_state("sensor.ms_living_room_burglar", "3") %}
          Tamper
        {% else %}
          Still
        {% endif %}
    family_room_motion:
      friendly_name: Family Room Motion
      value_template: >-
        {% if is_state("sensor.ms_family_room_burglar", "8") %}
          Motion
        {% elif is_state("sensor.ms_family_room_burglar", "3") %}
          Tamper
        {% else %}
          Still
        {% endif %}
    kitchen_motion:
      friendly_name: Kitchen Motion
      value_template: >-
        {% if is_state("sensor.ms_kitchen_burglar", "8") %}
          Motion
        {% elif is_state("sensor.ms_kitchen_burglar", "3") %}
          Tamper
        {% else %}
          Still
        {% endif %}
    basement_motion:
      friendly_name: Basement Motion
      value_template: >-
        {% if is_state("sensor.ms_basement_burglar", "8") %}
          Motion
        {% elif is_state("sensor.ms_basement_burglar", "3") %}
          Tamper
        {% else %}
          Still
        {% endif %}

#
# Composite Motion Sensors
#
    downstairs_motion:
      friendly_name: Downstairs Motion
      value_template: >-
        {% if is_state("sensor.ms_living_room_burglar", "8") or is_state("sensor.ms_family_room_burglar", "8") or is_state("sensor.ms_kitchen_burglar", "8") %}
          Motion
        {% else %}
          Still
        {% endif %}
#
# Filtered Motion Sensors
#
    downstairs_motion_filtered:
      friendly_name: Downstairs Motion
      value_template: >-
        {% if is_state("input_boolean.motion_downstairs", "on") %}
          Motion
        {% else %}
          Still
        {% endif %}
    basement_motion_filtered:
      friendly_name: Basement Motion
      value_template: >-
        {% if is_state("input_boolean.motion_basement", "on") %}
          Motion
        {% else %}
          Still
        {% endif %}
